CREATE DATABASE University

USE University

CREATE TABLE Majors(
	[MajorID] INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Students(
	[StudentID] INT IDENTITY PRIMARY KEY,
	[StudentNumber] VARCHAR(10) NOT NULL,
	[StudentName] NVARCHAR(50) NOT NULL,
	[ManagerID] INT NOT NULL FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Payments(
	[PaymentID] INT IDENTITY PRIMARY KEY,
	[PaymentDate] DATETIME2 NOT NULL,
	[PaymentAmount] DECIMAL(15, 2) NOT NULL,
	[StudentID] INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID)
)

CREATE TABLE Subjects(
	[SubjectID] INT IDENTITY PRIMARY KEY,
	[SubjectName] NVARCHAR(80) NOT NULL
)

CREATE TABLE Agenda(
	[StudentID] INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID),
	[SubjectID] INT NOT NULL FOREIGN KEY REFERENCES Subjects(SubjectID),
	PRIMARY KEY(StudentID, SubjectID)
)